### ISSUE TITLE
(Easy) Change a successful refresh call to be when the status code is < 300 as opposed to === 200

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-website#15]
In the [onUnauthorisedResponse function](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/index.ts#L467), in index.ts, we check if the response from the refresh API call is === 200. This results in an issue where if the user instead sends something like 201, it stops working.

We want to change that to check if the response is < 300.

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by rishabhpoddar** [comment]
Hi @rahullli . Sure! I have assigned it to you. Please find the updated first comment for more details.

**Comment by rishabhpoddar** [comment]
@rahullli , are you still working on this issue please?

**Comment by geeks5551** [comment]
Hey, can I contribute to the required issue? looks very interesting

**Comment by rishabhpoddar** [comment]
Hello @geeks5551. There is already a pull request for this issue. If you want, you can work on https://github.com/supertokens/supertokens-node/issues/10 - which is for NodeJS, is far more interesting and challenging than this one. If you are interested, please comment on that issue, and I will fill you in with the details :)
