### ISSUE TITLE
Using cached proxy causes issue with front-token change

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-website#155]
The frontend react app is served on localhost:3000. The backend is running on localhost:5000. The frontend also proxies request to localhost:5000 (via the proxy: "http://localhost:5000" setting in package.json).

Now if the apiDomain is (incorrectly) set to localhost:3000, it all still works (cause of the proxy), but it causes issues where the front-token value randomly changes to the older logged in session. It seems like the issue is to do with 304 status code being returned from the route where the main react app is loaded (localhost:3000).

**Comment by porcellus** [comment]
I could not reproduce this; I'm likely missing some piece of the setup.
A few more questions:
- was this a regular CRA app?
- did a 304 occur on anything that updated the token? I could not trigger it like that.
- when did this "revert" occur?
- was this on the SDK's main or the session claims version?
- was this app using a service worker?

How I tried to reproduce this:
- set up proxy as described
- set the `apiDomain` to the "wrong" value
- changed the access token payload with a fetch and refreshed it a few times.
- repeated the last step with different timings, repetitions, hard-refresh, soft-refresh, cache on/off, etc.

**Comment by rishabhpoddar** [comment]
> was this a regular CRA app?

Not sure.

> did a 304 occur on anything that updated the token? I could not trigger it like that.

From the response headers of 304, there was no front-token. But in the frontend lib's debug logs it showed that the URL to query was localhost:3000 (which returned 304), and then right after the query was done, it printed out setting sFrontToken=...

> when did this "revert" occur?

During top level navigation of the app. But since our interceptors dont run in that case, i'm not really sure.

> was this on the SDK's main or the session claims version?

main version. Not session claims version

> was this app using a service worker?

Not sure. But based on their setup, it didn't look like it. It was a simple frontend

**Comment by porcellus** [comment]
I still can't reproduce this even using navigation (with and without react-router-dom).
Without asking for a reproduction repo (or further code/info):
- I could only get the default proxy thing in CRA to respond with a 304 if there were no changes to the cookies.
- The only way the front token gets set is if we update the access token (and the cookies)
Combining these two, the dev-server should never cache responses like this.

The only extra thing we could do/add is to add a "Cache-Control" header to our responses, but that doesn't feel appropriate to do from inside the SDK. That'd likely solve this and we can recommend this to anyone who comes across this problem.

**Comment by rishabhpoddar** [comment]
hmm. okay. Since we can't repro this, im closing this for now.
