### ISSUE TITLE
(Easy) Allow the user to give just the API URL in `init` function call

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-website#17]
## I don't think this change is a necessary since it adds confusion in terms of communication in docs. For example, the user doesn't pass the refresh URL anymore, so the param cannot be called refreshTokenUrl, so we can raname it to apiEndpoint. But, in case they need to pass a custom refresh path, then they will be passing the whole URL, in which case, apiEndpoint is not a good name.

The `init` function call can be seen [here for `fetch`](https://supertokens.io/docs/website/fetch/init) and [here for `axios`](https://supertokens.io/docs/website/axios/init).

As of now, the `refreshTokenUrl ` must be a full path to the user's refresh API endpoint. Instead, we need to change it so that if they give:
- `https://api.example.com` or `https://api.example.com/`, [this line](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/axios.ts#L181) assigns `https://api.example.com/session/refresh` to `AuthHttpRequest.refreshTokenUrl`, and similarly for `index.ts`

- `https://api.example.com/some/other/path`,  [this line](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/axios.ts#L181) assigns `https://api.example.com/some/other/path`  to `AuthHttpRequest.refreshTokenUrl`, and similarly for `index.ts`.

Essentially, we want them to just give the API domain for ease of use.

**Important: We should also change the parameter name from `refreshTokenUrl` to `apiEndpoint` since that is more accurate now.**

This issue will also require to write some tests [for `axios`](https://github.com/supertokens/supertokens-website/blob/master/test/axios.test.js) and [for `fetch`](https://github.com/supertokens/supertokens-website/blob/master/test/fetch.test.js) which check that the right URL is assigned given various inputs. You could create a new function in `axios.ts` and `index.ts` to return the value of `refreshTokenUrl` that was assigned.

**Comment by rishabhpoddar** [comment]
hey @HunainHumail. Awesome! I have assigned the task to you, and please see the updated first comment for more details.

**Comment by HunainHumail** [comment]
Sure !! Thanks

**Comment by rishabhpoddar** [comment]
@HunainHumail , I don't think this change is a necessary one since it adds confusion in terms of communication in docs. For example, the user doesn't pass the refresh URL anymore, so the param cannot be called `refreshTokenUrl`, so we can raname it to `apiEndpoint`. But, in case they need to pass a custom refresh path, then they will be passing the whole URL, in which case, `apiEndpoint` is not a good name.

**Comment by rishabhpoddar** [comment]
@HunainHumail apologies for the confusion.
