### ISSUE TITLE
Fetch interceptor breaks fetch api.

### ISSUE THREAD

**Issue by Urbansson** [supertokens/supertokens-website#214]
## Bug description

When making calls using `fetch` with a `URL` object the call fails with the following error:
```ts
TypeError: url.clone is not a function
```
The docs in MDN says that fetch should support one of the following resource:
>A string or any other object with a [stringifier](https://developer.mozilla.org/en-US/docs/Glossary/Stringifier) — including a [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) object — that provides the URL of the resource you want to fetch.
>A [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object.

By modifying the fetch method making some resources not support might break applications on unpredictable ways.
## Steps to reproduce the issue

To reproduce the issue simply execute the following code after calling `supertokens.Init()`.

```js
fetch(new URL(("https://localhost:3000/index.html")))
  .then(() => {console.log("fetched")})
  .catch(err => console.log(err))
```

## Code that may be the issue

The issue is located at:
https://github.com/supertokens/supertokens-website/blob/ee861842b8a7f933477d43f0ff772372b53f9f09/lib/ts/recipeImplementation.ts#L33-L42

Where a `URL`  objects is unsafely casted to a `Request` object.

**Comment by rishabhpoddar** [comment]
This should have been fixed in supertokens-website sdk version >= 16.0.9
