### ISSUE TITLE
Documentation / Implementation mismatch

### ISSUE THREAD

**Issue by eweitnauer** [supertokens/supertokens-website#4]
In contradiction to the [API docs](https://supertokens.github.io/supertokens-website/docs/fetch/verifying-session), which say that `sessionPossiblyExists` returns a boolean, it [actually returns a Promise](https://github.com/supertokens/supertokens-website/blob/master/index.ts#L295).

Not only did this trip me up as I didn't expect it from reading the docs, it also seems to complicate things unnecessarily since the `sessionPossiblyExists` method does not actually do anything asynchronous. I'd suggest removing the `async` from the method.

**Comment by rishabhpoddar** [comment]
Thank you for pointing out this issue. It has been fixed in the latest version - 3.2.8 which has been released to npm.
