### ISSUE TITLE
Documentation Recipie Design

### ISSUE THREAD

**Issue by mufassirkazi** [supertokens/supertokens-website#44]
## Designs

Desktop: https://zpl.io/bom7jQm
Desktop (hover state): https://zpl.io/2vRXxv7
Tab: https://zpl.io/aME3rJz
Mobile: https://zpl.io/brqODBr

**Note: Please ignore the navigation (l.h.s) and only take values of the recipe boxes.**

**Comment by makerboiAdi** [comment]
Please show iteration where the image is of the actual UI (i.e. what each of these things look like for the end user - like the signup / input fields)

**Comment by mufassirkazi** [comment]
https://zpl.io/25PmDk3

cc: @makerboiAdi

**Comment by rishabhpoddar** [comment]
- I think you should put emailpassword + social login first
- Add more providers to emailpassword + social login. It looks weird with just one
- Changed text "Session Management" -> "Only Session Management"
- One issue for mobile view is that the user has to scroll to see all the recipes. Can we provide a different view on mobile that takes up much lesser space?
- Consider putting the full UI for each recipe instead of just the input field boxes. You can take screenshots of the UI from their demo sites.

**Comment by mufassirkazi** [comment]
Desktop: https://zpl.io/bom7jQm
Desktop (hover state): https://zpl.io/2vRXxv7
Tab: https://zpl.io/aME3rJz
Mobile: https://zpl.io/brqODBr

If everyone agrees with these, I'll update the parent comment.

**Comment by rishabhpoddar** [comment]
- I prefer showing sign in UI - just more the norm in my head
- The social login UI should also have a heading. I believe it's sign in / up
- Rest looks good IMO

**Comment by makerboiAdi** [comment]
Do you think by saying "only session management" people will wonder whether the others have sessions or not?

**Comment by rishabhpoddar** [comment]
Yea.. It may be confusing. But I think the word "Only" resolves some of the confusion? Also, if that happens, maybe we will find out soon enough? Also, those recipes will have a section for sessions, so if they see that, they will realise that sessions is included?

Alternatively, we could add that "session is included" in the subtext of those recipes on this page?

**Comment by mufassirkazi** [comment]
Did the latest change recommendations i.e - Showing 'Sign in' UI by default and adding heading for social login UI. 

To answer Advait's query, added "with sessions" to the subheading of each recipe. For the session management recipe, added "no login" to make it clear. 

Updated parent comment.

**Comment by rishabhpoddar** [comment]
https://github.com/supertokens/main-website/pull/344#issuecomment-814914069

**Comment by Infi-Knight** [comment]
https://github.com/supertokens/main-website/pull/349

**Comment by rishabhpoddar** [comment]
@Infi-Knight remove the loader that shows up on this page initially. It's not needed.

**Comment by Infi-Knight** [comment]
https://github.com/supertokens/main-website/compare/ravi-recipe-loader?expand=1

**Comment by Infi-Knight** [comment]
https://github.com/supertokens/main-website/pull/351

**Comment by rishabhpoddar** [comment]
@mufassirkazi please test on safari and see if this is fine. It's been pushed to production

**Comment by mufassirkazi** [comment]
UI is fine. Ravi has to add analytics. Otherwise, this issue can be closed.

**Comment by rishabhpoddar** [comment]
@Infi-Knight need to do analytics.
