### ISSUE TITLE
how to support SWR? even urql of graphql?

### ISSUE THREAD

**Issue by chenkaiC4** [supertokens/supertokens-website#56]
hi, this pkg container `addAxiosInterceptors` func to support axios, but if i use [swr](https://swr.vercel.app/), how to auto fix the cookie items? maybe some doc to tell us to how to do. so if i want to use [urlq](https://formidable.com/open-source/urql/) for graphql queries, i can do by myself.

**Comment by rishabhpoddar** [comment]
Do swr and urlq use `fetch` internally? If yes, then you don't have to do anything, and the interceptors for fetch are added automatically when you call `Session.init()`

**Comment by chenkaiC4** [comment]
@rishabhpoddar thanks, i will to confirm this~

**Comment by chenkaiC4** [comment]
yeah, thanks @rishabhpoddar, nice work for you have made the `fetch` and `axios` support.

urql use fetch default. And swr(my mistake) is just a react hook, which can use any query lib if it return a Promise.

so every thing should work well togather.
