### ISSUE TITLE
Version progression is wrong on npm repository

### ISSUE THREAD

**Issue by gusfune** [supertokens/supertokens-website#63]
I just noticed that my `yarn upgrade-interactive` was suggesting moving from version 7.2.1 to 5.1.1. Doing some digging it seems the wrong tag was placed in npm package: https://www.npmjs.com/package/supertokens-website?activeTab=versions

<img width="726" alt="Screen Shot 2021-06-14 at 08 56 58" src="https://user-images.githubusercontent.com/1147240/121851637-a8ba5a80-ccee-11eb-819b-ca960a9354e5.png">

**Comment by rishabhpoddar** [comment]
@gusfune thanks for pointing this issue out.. it was an issue with us not using the `--tag` option when running `npm publish`. I have released a new latest version (v7.2.2) for now which is identical to (v7.2.1) except for a bump in the last version. 

We will work on fixing out public process to take this into account.

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya we need to upgrade all the publish CICD script to use `npm publish --tag <tag>` in case we are not publishing the latest version. In case of latest version, we can simply continue to use `npm publish`. This applies to:
- [ ] supertokens-website
- [ ] supertokens-auth-react
- [ ] supertokens-node
