### ISSUE TITLE
Add test for deleting cookies when core returns "UNAUTHORISED" response on call to refresh session

### ISSUE THREAD

**Issue by seniorquico** [supertokens/supertokens-website#71]
In our C# backend implementation, we missed a call to delete the frontend cookies when the core returned an UNAUTHORISED response when the frontend was calling the refresh session endpoint on the backend. It would be awesome to have a test for this specific scenario, as it's quite difficult for us to reproduce within the backend itself (depends on an UNAUTHORISED response from the core).

**Comment by rishabhpoddar** [comment]
Test added and merged with master branch.
