### ISSUE TITLE
%s/let/const/g

### ISSUE THREAD

**Issue by madflow** [supertokens/supertokens-website#8]
Hi there!

I do not want to fill out a form to contribute - so just a quick hint.

In the NodeJs docs: https://supertokens.io/docs/nodejs/installation

You can/should replace all occurrences of `let` with `const`  - as far as I can see you do never assign a new value to the variables in question. Your app will still run fine - it propagates bad habits though ;).

**Comment by rishabhpoddar** [comment]
Thanks @madflow. Will add this to our changes backlog. Will close this issue since it's not actually related to the code in this repository.
