### ISSUE TITLE
Is verifySession making a call to CORE server each time?

### ISSUE THREAD

**Issue by ambrt** [supertokens/supertokens-website#96]
I'm considering moving all auth to SuperTokens self hosted core.

Now my question is if i use verifySession() that guards my user's data API
is it making additional call to core server evertime?

Basically i see that there are 3 servers involved - front, back and core.

My goal would be to Log In user on front end by calling core
and then just call  backend server (for users data) directly from front end.
(Without calling core server on each backend verifySession() )

Is this how SDK works? Or every time i use verifySession() , a call to core will be made?

Longer explanation: I consider using two Heroku dynos one for core and one for backend, 
with  CloudFlare worker for serving frontend.

If i would make two calls (back & core) for each API call,that would slow down
app and would increase time to get data to user by ~50%.
(And would lessen the worth of having serverless app in first place )

**Comment by rishabhpoddar** [comment]
Hi @ambrt ,

> Basically i see that there are 3 servers involved - front, back and core.

The backend server (not the core, but backend) doesn't actually need to be its own server. You simply have to integrate  your existing backend API layer with our backend SDK.

> My goal would be to Log In user on front end by calling core

The frontend never talks to the core directly. It's always through your backed API layer. Your frontend would call the APIs exposed by our backend SDK, which would then call the core as needed.

> Or every time i use verifySession() , a call to core will be made?

No. Session verification doesn't require a call to the core. The way it works is that when the backend process starts, it queries the core once to get the public key used to verify the session. This key is then stored in memory and used for session verification each time.

Now keeping in mind that you have a serverless architecture, each time a request is sent to the backend, a new process would start. This means it would query the core to get the public key each time. However, if you keep the workers "warm", then this problem would be solved.

I'm closing this issue for now, but feel free to reopen to ask more questions. You can even join our discord server to ask questions: https://supertokens.io/discord
